name: roteipro
description: Aplicativo de gerenciamento de rotas de caminhões
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  get_it: ^7.6.4
  mask_text_input_formatter: ^2.5.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2
  intl: ^0.19.0
  flutter_verification_code: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
