// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRiFHilzInvgp_dICKg5gZzpW2Kuqrlg',
    appId: '1:810666233216:web:7129c35fccfb1088364565',
    messagingSenderId: '810666233216',
    projectId: 'rotei-pro',
    authDomain: 'rotei-pro.firebaseapp.com',
    storageBucket: 'rotei-pro.firebasestorage.app',
    measurementId: 'G-FJ02QLKVEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZiAV2CsswR5CobDKwRg6thjDBIY-CQD8',
    appId: '1:810666233216:android:153accca026e3442364565',
    messagingSenderId: '810666233216',
    projectId: 'rotei-pro',
    storageBucket: 'rotei-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbiAYPoiyb9_cJRTzu9Bc2H-uuzKEHUQU',
    appId: '1:810666233216:ios:8873f528ff5fa000364565',
    messagingSenderId: '810666233216',
    projectId: 'rotei-pro',
    storageBucket: 'rotei-pro.firebasestorage.app',
    iosBundleId: 'com.example.roteipro',
  );

}